namespace ClassicUO.Game
{
    internal static class Jokes
    {

        public static readonly string[] UltimaOnlineJokes = new string[]
        {
            "Why did the chicken cross the road in Britannia? To avoid getting PKed!",
            "Why don't skeletons fight each other in Britannia? They don't have the guts.",
            "Why did the lich become a comedian? He wanted to tickle your funny bone!",
            "Why did the mage refuse to fight? He didn't want to spell trouble.",
            "Why did the thief bring a ladder to the dungeon? To take his stealing to new heights!",
            "Why did the warrior go to school? To improve his swordsmanship!",
            "Why did the bard get kicked out of the tavern? He couldn't hold his ale.",
            "Why did the blacksmith become a musician? He wanted to forge a new career.",
            "Why did the tailor become a detective? He was good at following threads.",
            "Why did the fisherman get promoted? He was reeling in success.",
            "Why did the miner become a poet? He had a way with ores.",
            "Why did the alchemist start a bakery? He wanted to turn dough into gold.",
            "Why did the tamer bring a dragon to the party? To break the ice!",
            "Why did the healer become a chef? He was good at making potions.",
            "Why did the carpenter become a comedian? He had a knack for nailing punchlines.",
            "Why did the ranger get lost? He couldn't find his bearings.",
            "Why did the necromancer get a pet dog? To have a bone to pick with.",
            "Why did the paladin become a teacher? He wanted to instill virtues.",
            "Why did the druid start a garden? He wanted to grow his own reagents.",
            "Why did the assassin become a barber? He was good at close shaves.",
            "Why did the knight become a lawyer? He was good at defending.",
            "Why did the archer become a tailor? He was good at threading the needle.",
            "Why did the bard get a job at the bank? He was good at making notes.",
            "Why did the mage open a bakery? He wanted to make magic muffins.",
            "Why did the thief become a locksmith? He wanted to pick up a new skill.",
            "Why did the warrior become a chef? He wanted to tenderize his enemies.",
            "Why did the blacksmith become a jeweler? He wanted to forge new relationships.",
            "Why did the tailor become a painter? He wanted to create a new canvas.",
            "Why did the fisherman become a writer? He had a way with lines.",
            "Why did the miner become a sculptor? He wanted to carve out a new career.",
            "Why did the alchemist become a bartender? He wanted to mix things up.",
            "Why did the tamer become a zookeeper? He wanted to tame the wild.",
            "Why did the healer become a pharmacist? He wanted to dispense potions.",
            "Why did the carpenter become an architect? He wanted to build a better future.",
            "Why did the ranger become a tour guide? He knew all the best spots.",
            "Why did the necromancer become a comedian? He had a deadpan delivery.",
            "Why did the paladin become a judge? He wanted to uphold justice.",
            "Why did the druid become a farmer? He wanted to cultivate the land.",
            "Why did the assassin become a tailor? He was good at cutting corners.",
            "Why did the knight become a firefighter? He wanted to extinguish evil.",
            "Why did the archer become a musician? He was good at hitting the right notes.",
            "Why did the bard become a librarian? He loved to tell stories.",
            "Why did the mage become a scientist? He wanted to experiment with magic.",
            "Why did the thief become a magician? He was good at making things disappear.",
            "Why did the warrior become a bodyguard? He wanted to protect and serve.",
            "Why did the blacksmith become a chef? He wanted to forge new flavors.",
            "Why did the tailor become a designer? He wanted to create new fashions.",
            "Why did the fisherman become a sailor? He wanted to explore new waters.",
            "Why did the miner become a jeweler? He wanted to find hidden gems.",
            "Why did the alchemist become a chef? He wanted to create culinary magic.",
            "Why did the mage refuse to use the moongate? He didn't want to be gated into trouble!",
            "Why dost thou not trust a necromancer? For they always have a bone to pick!",
            "Why did the tamer bring a dragon to the tavern? To break the ice!",
            "Why dost dexxers not like tamers? They can't handle the beastly competition!",
            "Why did the lich become a comedian? He wanted to tickle your funny bone!",
            "Why dost thou not trust a reagent merchant? For they always charge an arm and a leg!",
            "Why did the warrior go to school? To improve his swordsmanship!",
            "Why dost mages and necromancers never get along? They always spell trouble for each other!",
            "Why did the bard get kicked out of the tavern? He couldn't hold his ale!",
            "Why dost thou not play cards with a tamer? They always have a wild card!",
            "Why did the fisherman get promoted? He was reeling in success!",
            "Why dost thou not trust a moongate? For it might lead thee astray!",
            "Why did the alchemist start a bakery? He wanted to turn dough into gold!",
            "Why dost dexxers always win arguments? They have the sharpest points!",
            "Why did the healer become a chef? He was good at making potions!",
            "Why dost thou not trust a necromancer's jokes? They are always deadpan!",
            "Why did the carpenter become a comedian? He had a knack for nailing punchlines!",
            "Why dost mages love moongates? They are always looking for a portal to new adventures!",
            "Why did the paladin become a teacher? He wanted to instill virtues!",
            "Why dost tamers always have the best stories? They are full of wild tales!",
            "Why did the assassin become a barber? He was good at close shaves!",
            "Why dost thou not trust a mage's cooking? They always add too many reagents!",
            "Why did the archer become a tailor? He was good at threading the needle!",
            "Why dost necromancers never get lost? They always follow the bone road!",
            "Why did the mage open a bakery? He wanted to make magic muffins!",
            "Why dost dexxers always carry a map? They don't want to get lost in the melee!",
            "Why did the warrior become a chef? He wanted to tenderize his enemies!",
            "Why dost tamers always have the best pets? They know how to pick the cream of the crop!",
            "Why did the tailor become a painter? He wanted to create a new canvas!",
            "Why dost mages always have clean robes? They know how to cast a cleaning spell!",
            "Why did the alchemist become a bartender? He wanted to mix things up!",
            "Why dost necromancers never get invited to parties? They always bring a ghastly guest!",
            "Why did the healer become a pharmacist? He wanted to dispense potions!",
            "Why dost dexxers always have the best armor? They know how to take a hit!",
            "Why did the carpenter become an architect? He wanted to build a better future!",
            "Why dost tamers always have the best mounts? They know how to tame the wild!",
            "Why did the necromancer become a comedian? He had a deadpan delivery!",
            "Why dost mages always have the best spells? They know how to cast a wide net!",
            "Why did the druid become a farmer? He wanted to cultivate the land!",
            "Why dost dexxers always have the best weapons? They know how to forge a good blade!",
            "Why did the knight become a firefighter? He wanted to extinguish evil!",
            "Why dost tamers always have the best stories? They know how to spin a wild tale!",
            "Why did the bard become a librarian? He loved to tell stories!",
            "Why dost mages always have the best potions? They know how to brew a good mix!",
            "Why did the thief become a magician? He was good at making things disappear!",
            "Why dost dexxers always have the best shields? They know how to block a hit!",
            "Why did the blacksmith become a chef? He wanted to forge new flavors!",
            "Why dost tamers always have the best pets? They know how to pick the cream of the crop!",
            "Why did the fisherman become a sailor? He wanted to explore new waters!",
            "Why dost mages always have the best reagents? They know how to gather the finest ingredients!",
            "Why did the dragon go to school? To improve his fire-breathing skills!",
            "Why don't liches ever get lost? They always follow the bone road!",
            "Why did the orc bring a ladder to the battle? To take his fighting to new heights!",
            "Why don't trolls ever get invited to parties? They always cause a ruckus!",
            "Why did the harpy become a singer? She had a voice that could charm anyone!",
            "Why don't gargoyles ever get tired? They are always stone-faced!",
            "Why did the ogre become a chef? He wanted to tenderize his enemies!",
            "Why don't skeletons fight each other? They don't have the guts!",
            "Why did the demon become a comedian? He had a devilish sense of humor!",
            "Why don't ettins ever get lost? They always have a second opinion!",
            "Why did the vampire become a banker? He wanted to make a killing!",
            "Why don't wraiths ever get tired? They are always full of spirit!",
            "Why did the giant spider become a weaver? She was good at spinning tales!",
            "Why don't zombies ever get promoted? They are always dead weight!",
            "Why did the cyclops become a jeweler? He had an eye for gems!",
            "Why don't mummies ever get lost? They always follow the band!",
            "Why did the sea serpent become a sailor? He wanted to explore new waters!",
            "Why don't reapers ever get tired? They are always rooted in place!",
            "Why did the balron become a judge? He was good at passing judgment!",
            "Why don't harpies ever get lost? They always follow the song!",
            "Why did the lich become a librarian? He loved to read ancient tomes!",
            "Why don't dragons ever get cold? They always have a warm heart!",
            "Why did the troll become a gardener? He was good at digging up trouble!",
            "Why don't gargoyles ever get scared? They are always stone-cold!",
            "Why did the ogre become a blacksmith? He wanted to forge new weapons!",
            "Why don't skeletons ever get tired? They are always bone-tired!",
            "Why did the demon become a lawyer? He was good at making deals!",
            "Why don't ettins ever get bored? They always have double the fun!",
            "Why did the vampire become a doctor? He wanted to take a bite out of illness!",
            "Why don't wraiths ever get lost? They always follow the wail!",
            "Why did the giant spider become a tailor? She was good at weaving!",
            "Why don't zombies ever get tired? They are always dead on their feet!",
            "Why did the cyclops become a watchmaker? He had an eye for detail!",
            "Why don't mummies ever get tired? They are always wrapped up in their work!",
            "Why did the sea serpent become a fisherman? He wanted to catch a big one!",
            "Why don't reapers ever get bored? They are always rooted in place!",
            "Why did the balron become a teacher? He was good at instilling fear!",
            "Why don't harpies ever get tired? They are always full of song!",
            "Why did the lich become a historian? He loved to recount ancient battles!",
            "Why don't dragons ever get bored? They always have a fiery personality!",
            "Why did the troll become a miner? He was good at digging up trouble!",
            "Why don't gargoyles ever get tired? They are always stone-faced!",
            "Why did the ogre become a wrestler? He wanted to grapple with his enemies!",
            "Why don't skeletons ever get bored? They are always bone-tired!",
            "Why did the demon become a politician? He was good at making deals!",
            "Why don't ettins ever get tired? They always have double the energy!",
            "Why did the vampire become a chef? He wanted to make a bloody good meal!",
            "Why don't wraiths ever get bored? They are always full of spirit!",
            "Why did the giant spider become a storyteller? She was good at spinning tales!",
            "Why don't zombies ever get lost? They always follow the crowd!",
            "A dragon walks into a bar. The bartender says, 'Why the long face?' The dragon replies, 'I just got burned in PvP.'",
            "How many liches does it take to change a lantern? None, they prefer the dark.",
            "A tamer and a dexxer walk into a bar. The bartender says, 'Is this a joke?'",
            "What do you call a mage who lost his staff? Unarmed.",
            "A necromancer and a paladin walk into a bar. The bartender says, 'We don't serve your kind here.' The necromancer says, 'Good, I don't eat.'",
            "How do you make a skeleton laugh? Tickle its funny bone.",
            "A troll walks into a bar and orders a drink. The bartender says, 'We don't serve trolls here.' The troll replies, 'Good, I brought my own.'",
            "What do you get when you cross a vampire with a snowman? Frostbite.",
            "A bard walks into a bar and starts playing. The bartender says, 'Can you play something else?' The bard replies, 'I only know one tune.'",
            "How do you know if a dragon is in your house? Your roof is on fire.",
            "A mage, a warrior, and a thief walk into a bar. The bartender says, 'What is this, a quest?'",
            "What do you call a necromancer with no friends? A bonehead.",
            "A tamer walks into a bar with a dragon. The bartender says, 'You can't bring that in here.' The tamer replies, 'It's my emotional support dragon.'",
            "How do you keep a lich in suspense? I'll tell you later.",
            "A paladin walks into a bar and orders a drink. The bartender says, 'We don't serve your kind here.' The paladin replies, 'Good, I don't drink.'",
            "What do you call a skeleton who won't work? Lazy bones.",
            "A troll walks into a bar and orders a drink. The bartender says, 'We don't serve trolls here.' The troll replies, 'Good, I brought my own.'",
            "How do you make a vampire smile? Show it a mirror.",
            "A bard walks into a bar and starts playing. The bartender says, 'Can you play something else?' The bard replies, 'I only know one tune.'",
            "How do you know if a dragon is in your house? Your roof is on fire.",
            "A mage, a warrior, and a thief walk into a bar. The bartender says, 'What is this, a quest?'",
            "What do you call a necromancer with no friends? A bonehead.",
            "A tamer walks into a bar with a dragon. The bartender says, 'You can't bring that in here.' The tamer replies, 'It's my emotional support dragon.'",
            "How do you keep a lich in suspense? I'll tell you later.",
            "A paladin walks into a bar and orders a drink. The bartender says, 'We don't serve your kind here.' The paladin replies, 'Good, I don't drink.'",
            "What do you call a skeleton who won't work? Lazy bones.",
            "A troll walks into a bar and orders a drink. The bartender says, 'We don't serve trolls here.' The troll replies, 'Good, I brought my own.'",
            "How do you make a vampire smile? Show it a mirror.",
            "A bard walks into a bar and starts playing. The bartender says, 'Can you play something else?' The bard replies, 'I only know one tune.'",
            "How do you know if a dragon is in your house? Your roof is on fire.",
            "A mage, a warrior, and a thief walk into a bar. The bartender says, 'What is this, a quest?'",
            "What do you call a necromancer with no friends? A bonehead.",
            "A tamer walks into a bar with a dragon. The bartender says, 'You can't bring that in here.' The tamer replies, 'It's my emotional support dragon.'",
            "How do you keep a lich in suspense? I'll tell you later.",
            "A paladin walks into a bar and orders a drink. The bartender says, 'We don't serve your kind here.' The paladin replies, 'Good, I don't drink.'",
            "What do you call a skeleton who won't work? Lazy bones.",
            "A troll walks into a bar and orders a drink. The bartender says, 'We don't serve trolls here.' The troll replies, 'Good, I brought my own.'",
            "How do you make a vampire smile? Show it a mirror.",
            "A bard walks into a bar and starts playing. The bartender says, 'Can you play something else?' The bard replies, 'I only know one tune.'",
            "How do you know if a dragon is in your house? Your roof is on fire.",
            "A mage, a warrior, and a thief walk into a bar. The bartender says, 'What is this, a quest?'",
            "What do you call a necromancer with no friends? A bonehead.",
            "A tamer walks into a bar with a dragon. The bartender says, 'You can't bring that in here.' The tamer replies, 'It's my emotional support dragon.'",
            "How do you keep a lich in suspense? I'll tell you later.",
            "A paladin walks into a bar and orders a drink. The bartender says, 'We don't serve your kind here.' The paladin replies, 'Good, I don't drink.'",
            "What do you call a skeleton who won't work? Lazy bones.",
            "A troll walks into a bar and orders a drink. The bartender says, 'We don't serve trolls here.' The troll replies, 'Good, I brought my own.'",
            "How do you make a vampire smile? Show it a mirror."
        };
    }
}