namespace ClassicUO.Game
{
    internal static class SpeechMerchantStrings
    {
        public static readonly string[] GeneralMerchantGreetings = new string[]
        {
            "Hello, traveler! How can I assist you today?",
            "Greetings! Looking for something special?",
            "Welcome! What can I do for you?",
            "Good day! Interested in some fine goods?",
            "Hello! How can I help you today?",
            "Greetings, adventurer! Need supplies?",
            "Welcome! What are you looking for?",
            "Good day! How can I be of service?",
            "Hello! Need any equipment?",
            "Greetings! What do you need?",
            "Welcome! How can I assist you?",
            "Good day! Looking for something?",
            "Hello! How can I help?",
            "Greetings! Need any items?",
            "Welcome! What can I offer you?",
            "Good day! How can I assist?",
            "Hello! Looking for supplies?",
            "Greetings! What do you seek?",
            "Welcome! How can I help?",
            "Good day! Need any goods?",
            "Hello! How can I assist?",
            "Greetings! Looking for items?",
            "Welcome! What do you need?",
            "Good day! How can I help?",
            "Hello! Need any supplies?"
        };

        public static readonly string[] BlackMarketMerchantGreetings = new string[]
        {
            "Psst, over here! Looking for something rare?",
            "Greetings, traveler. Interested in unique goods?",
            "Welcome to the black market. What do you seek?",
            "Good day. Looking for something special?",
            "Psst, need something you can't find elsewhere?",
            "Greetings, adventurer. Interested in rare items?",
            "Welcome to the black market. What can I offer you?",
            "Good day. Looking for unique goods?",
            "Psst, over here! Need something rare?",
            "Greetings, traveler. Interested in special items?",
            "Welcome to the black market. What do you need?",
            "Good day. Looking for rare goods?",
            "Psst, need something unique?",
            "Greetings, adventurer. Interested in rare goods?",
            "Welcome to the black market. What can I help you with?",
            "Good day. Looking for special items?",
            "Psst, over here! Need something special?",
            "Greetings, traveler. Interested in unique items?",
            "Welcome to the black market. What do you seek?",
            "Good day. Looking for unique goods?",
            "Psst, need something rare?",
            "Greetings, adventurer. Interested in special goods?",
            "Welcome to the black market. What can I offer you?",
            "Good day. Looking for rare items?",
            "Psst, over here! Need something unique?"
        };

        public static readonly string[] BankerGreetings = new string[]
        {
            "Hello, how can I assist with your finances today?",
            "Greetings! Need to make a deposit or withdrawal?",
            "Welcome! How can I help with your banking needs?",
            "Good day! Looking to manage your gold?",
            "Hello! How can I assist with your banking?",
            "Greetings, adventurer! Need to access your bank?",
            "Welcome! How can I help with your finances?",
            "Good day! Need to manage your currency?",
            "Hello! How can I assist with your gold?",
            "Greetings! Need to make a financial transaction?",
            "Welcome! How can I help with your banking?",
            "Good day! Looking to manage your funds?",
            "Hello! How can I assist with your money?",
            "Greetings! Need to access your bank account?",
            "Welcome! How can I help with your finances?",
            "Good day! Need to manage your gold?",
            "Hello! How can I assist with your banking?",
            "Greetings! Need to make a deposit or withdrawal?",
            "Welcome! How can I help with your currency?",
            "Good day! Looking to manage your funds?",
            "Hello! How can I assist with your money?",
            "Greetings! Need to access your bank?",
            "Welcome! How can I help with your finances?",
            "Good day! Need to manage your gold?",
            "Hello! How can I assist with your banking?"
        };

        public static readonly string[] ArmorerGreetings = new string[]
        {
            "Hello, looking for some sturdy armor?",
            "Greetings! Need protection for your adventures?",
            "Welcome! How can I help with your armor needs?",
            "Good day! Looking for some new gear?",
            "Hello! How can I assist with your armor?",
            "Greetings, adventurer! Need some protection?",
            "Welcome! How can I help with your armor needs?",
            "Good day! Looking for some new armor?",
            "Hello! How can I assist with your gear?",
            "Greetings! Need some sturdy protection?",
            "Welcome! How can I help with your armor?",
            "Good day! Looking for some new gear?",
            "Hello! How can I assist with your protection?",
            "Greetings! Need some new armor?",
            "Welcome! How can I help with your gear?",
            "Good day! Looking for some sturdy armor?",
            "Hello! How can I assist with your protection?",
            "Greetings! Need some new gear?",
            "Welcome! How can I help with your armor?",
            "Good day! Looking for some new protection?",
            "Hello! How can I assist with your gear?",
            "Greetings! Need some sturdy armor?",
            "Welcome! How can I help with your protection?",
            "Good day! Looking for some new armor?",
            "Hello! How can I assist with your gear?"
        };

        public static readonly string[] WeaponSmithGreetings = new string[]
        {
            "Hello, looking for a new weapon?",
            "Greetings! Need a new blade or bow?",
            "Welcome! How can I help with your weapon needs?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?",
            "Greetings, adventurer! Need a new weapon?",
            "Welcome! How can I help with your weapon needs?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?",
            "Greetings! Need a new blade or bow?",
            "Welcome! How can I help with your weapon?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?",
            "Greetings! Need a new weapon?",
            "Welcome! How can I help with your weapon needs?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?",
            "Greetings! Need a new blade or bow?",
            "Welcome! How can I help with your weapon?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?",
            "Greetings! Need a new weapon?",
            "Welcome! How can I help with your weapon needs?",
            "Good day! Looking for some new firepower?",
            "Hello! How can I assist with your weapons?"
        };

        public static readonly string[] PotionVendorGreetings = new string[]
        {
            "Hello, looking for some potions?",
            "Greetings! Need some healing or mana potions?",
            "Welcome! How can I help with your potion needs?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?",
            "Greetings, adventurer! Need some potions?",
            "Welcome! How can I help with your potion needs?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?",
            "Greetings! Need some healing or mana potions?",
            "Welcome! How can I help with your potions?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?",
            "Greetings! Need some potions?",
            "Welcome! How can I help with your potion needs?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?",
            "Greetings! Need some healing or mana potions?",
            "Welcome! How can I help with your potions?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?",
            "Greetings! Need some potions?",
            "Welcome! How can I help with your potion needs?",
            "Good day! Looking for some beneficial potions?",
            "Hello! How can I assist with your potions?"
        };

        public static readonly string[] SpellVendorGreetings = new string[]
        {
            "Hello, looking for some spells?",
            "Greetings! Need some scrolls or spellbooks?",
            "Welcome! How can I help with your spell needs?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?",
            "Greetings, adventurer! Need some spells?",
            "Welcome! How can I help with your spell needs?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?",
            "Greetings! Need some scrolls or spellbooks?",
            "Welcome! How can I help with your spells?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?",
            "Greetings! Need some spells?",
            "Welcome! How can I help with your spell needs?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?",
            "Greetings! Need some scrolls or spellbooks?",
            "Welcome! How can I help with your spells?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?",
            "Greetings! Need some spells?",
            "Welcome! How can I help with your spell needs?",
            "Good day! Looking for some magical items?",
            "Hello! How can I assist with your spells?"
        };

        public static readonly string[] TailorGreetings = new string[]
        {
            "Hello, looking for some new clothes?",
            "Greetings! Need some fabric-based items?",
            "Welcome! How can I help with your tailoring needs?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?",
            "Greetings, adventurer! Need some new clothes?",
            "Welcome! How can I help with your tailoring needs?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?",
            "Greetings! Need some fabric-based items?",
            "Welcome! How can I help with your clothes?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?",
            "Greetings! Need some new clothes?",
            "Welcome! How can I help with your tailoring needs?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?",
            "Greetings! Need some fabric-based items?",
            "Welcome! How can I help with your clothes?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?",
            "Greetings! Need some new clothes?",
            "Welcome! How can I help with your tailoring needs?",
            "Good day! Looking for some new outfits?",
            "Hello! How can I assist with your clothing?"
        };

        public static readonly string[] BlacksmithGreetings = new string[]
        {
            "Hello, looking for some metal items?",
            "Greetings! Need some weapons or armor?",
            "Welcome! How can I help with your blacksmithing needs?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?",
            "Greetings, adventurer! Need some metal items?",
            "Welcome! How can I help with your blacksmithing needs?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?",
            "Greetings! Need some weapons or armor?",
            "Welcome! How can I help with your blacksmithing?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?",
            "Greetings! Need some metal items?",
            "Welcome! How can I help with your blacksmithing needs?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?",
            "Greetings! Need some weapons or armor?",
            "Welcome! How can I help with your blacksmithing?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?",
            "Greetings! Need some metal items?",
            "Welcome! How can I help with your blacksmithing needs?",
            "Good day! Looking for some metal gear?",
            "Hello! How can I assist with your blacksmithing?"
        };

        public static readonly string[] HerbalistGreetings = new string[]
        {
            "Hello, looking for some herbs?",
            "Greetings! Need some ingredients for potions?",
            "Welcome! How can I help with your herbal needs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?",
            "Greetings, adventurer! Need some herbs?",
            "Welcome! How can I help with your herbal needs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?",
            "Greetings! Need some ingredients for potions?",
            "Welcome! How can I help with your herbs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?",
            "Greetings! Need some herbs?",
            "Welcome! How can I help with your herbal needs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?",
            "Greetings! Need some ingredients for potions?",
            "Welcome! How can I help with your herbs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?",
            "Greetings! Need some herbs?",
            "Welcome! How can I help with your herbal needs?",
            "Good day! Looking for some alchemy supplies?",
            "Hello! How can I assist with your herbs?"
        };

        public static readonly string[] JewelerGreetings = new string[]
        {
            "Hello, looking for some jewelry?",
            "Greetings! Need some gems or valuable items?",
            "Welcome! How can I help with your jewelry needs?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?",
            "Greetings, adventurer! Need some jewelry?",
            "Welcome! How can I help with your jewelry needs?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?",
            "Greetings! Need some gems or valuable items?",
            "Welcome! How can I help with your jewelry?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?",
            "Greetings! Need some jewelry?",
            "Welcome! How can I help with your jewelry needs?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?",
            "Greetings! Need some gems or valuable items?",
            "Welcome! How can I help with your jewelry?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?",
            "Greetings! Need some jewelry?",
            "Welcome! How can I help with your jewelry needs?",
            "Good day! Looking for some valuable items?",
            "Hello! How can I assist with your jewelry?"
        };

        public static readonly string[] GeneralMerchantFarewells = new string[]
     {
            "Thank you for your purchase! Safe travels!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Safe travels!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Safe travels!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Safe travels!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Safe travels!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
     };

        public static readonly string[] BlackMarketMerchantFarewells = new string[]
        {
            "Thank you for your purchase! Stay safe!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay safe!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay safe!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay safe!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay safe!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] BankerFarewells = new string[]
        {
            "Thank you for your business! Safe travels!",
            "Thanks for banking with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your transaction! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for banking! Farewell!",
            "Your business is valued! Safe travels!",
            "Thank you! Visit us again soon!",
            "Thanks for your transaction! Take care!",
            "Thank you! Safe travels!",
            "Thanks for banking! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your transaction! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for banking! Farewell!",
            "Your business is valued! Safe travels!",
            "Thank you! Visit us again soon!",
            "Thanks for your transaction! Take care!",
            "Thank you! Safe travels!",
            "Thanks for banking! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your transaction! Safe journey!"
        };

        public static readonly string[] ArmorerFarewells = new string[]
        {
            "Thank you for your purchase! Stay protected!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and stay safe!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay protected!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay protected!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and stay safe!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay protected!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay protected!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and stay safe!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] WeaponSmithFarewells = new string[]
        {
            "Thank you for your purchase! Wield it well!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Wield it well!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Wield it well!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Wield it well!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Wield it well!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] PotionVendorFarewells = new string[]
        {
            "Thank you for your purchase! Stay healthy!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay healthy!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay healthy!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay healthy!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay healthy!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] SpellVendorFarewells = new string[]
        {
            "Thank you for your purchase! Cast wisely!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Cast wisely!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Cast wisely!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Cast wisely!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Cast wisely!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] TailorFarewells = new string[]
        {
            "Thank you for your purchase! Stay stylish!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay stylish!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay stylish!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay stylish!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay stylish!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] BlacksmithFarewells = new string[]
        {
            "Thank you for your purchase! Stay strong!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay strong!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay strong!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Stay strong!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Stay strong!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] HerbalistFarewells = new string[]
        {
            "Thank you for your purchase! Happy brewing!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Happy brewing!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Happy brewing!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Happy brewing!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Happy brewing!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };

        public static readonly string[] JewelerFarewells = new string[]
        {
            "Thank you for your purchase! Shine bright!",
            "Thanks for shopping with us! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Shine bright!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Shine bright!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!",
            "Thank you! Come back anytime!",
            "Thanks for shopping! Farewell!",
            "Your business is valued! Shine bright!",
            "Thank you! Visit us again soon!",
            "Thanks for your purchase! Take care!",
            "Thank you! Shine bright!",
            "Thanks for shopping! Come back soon!",
            "Your business is appreciated! Farewell!",
            "Thank you! Take care and good luck!",
            "Thanks for your purchase! Safe journey!"
        };
    }
}
