// SPDX-License-Identifier: BSD-2-Clause
// 3DCUO prototype — UO graphic + Layer → Sidekick part list lookup.
// Loaded once from Data/uo-sidekick-map.json (generated by
// tools/scripts/build-uo-sidekick-runtime-map.py from uo-equipment-catalog.xlsx).
// Used by AttachmentRenderer.AutoFromEquipment to drive slot indices off the
// player's currently-equipped items.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

#nullable disable

namespace ClassicUO.Renderer.Renderer3D
{
    internal readonly struct SidekickPartRef
    {
        public readonly AttachSlotKind Slot;
        public readonly string Subfolder;   // e.g. "Hats" — must match AttachSlot.Subfolder
        public readonly string Rel;         // e.g. "FantasyKnights/SK_FANT_KNGT_01_22AHED_HU01.glb"

        public SidekickPartRef(AttachSlotKind slot, string subfolder, string rel)
        {
            Slot = slot;
            Subfolder = subfolder;
            Rel = rel;
        }
    }

    internal static class EquipmentSidekickMap
    {
        // graphic -> parts. Multiple Layer values may share a graphic in theory; in
        // practice the catalog has 1:1 (graphic -> name -> layer) so we key on
        // graphic alone and store the layer alongside for diagnostics.
        private static readonly Dictionary<int, List<SidekickPartRef>> _byGraphic = new();
        private static readonly Dictionary<int, string> _layerByGraphic = new(); // for logging
        private static bool _loaded;
        public static string LastError;
        public static int LoadedCount;

        public static void EnsureLoaded()
        {
            if (_loaded) return;
            _loaded = true;
            try
            {
                string path = ResolveJsonPath();
                if (path == null)
                {
                    LastError = "uo-sidekick-map.json not found";
                    Console.WriteLine($"[3DCUO] EquipmentSidekickMap: {LastError}");
                    return;
                }
                var json = File.ReadAllText(path);
                using var doc = JsonDocument.Parse(json);
                var root = doc.RootElement;
                if (!root.TryGetProperty("items", out var items)) return;

                foreach (var entry in items.EnumerateArray())
                {
                    if (!entry.TryGetProperty("graphic", out var gProp)) continue;
                    int graphic = gProp.GetInt32();

                    var parts = new List<SidekickPartRef>();
                    if (entry.TryGetProperty("slots", out var slotsProp))
                    {
                        foreach (var s in slotsProp.EnumerateArray())
                        {
                            string slotName = s.GetProperty("slot").GetString();
                            string subfolder = s.GetProperty("subfolder").GetString();
                            string rel = s.GetProperty("rel").GetString();
                            if (Enum.TryParse<AttachSlotKind>(slotName, out var kind))
                                parts.Add(new SidekickPartRef(kind, subfolder, rel));
                        }
                    }
                    if (parts.Count == 0) continue;

                    _byGraphic[graphic] = parts;
                    if (entry.TryGetProperty("layer", out var lProp) && lProp.ValueKind == JsonValueKind.String)
                        _layerByGraphic[graphic] = lProp.GetString();
                }
                LoadedCount = _byGraphic.Count;
                Console.WriteLine($"[3DCUO] EquipmentSidekickMap loaded: {LoadedCount} items from {path}");
            }
            catch (Exception ex)
            {
                LastError = ex.Message;
                Console.WriteLine($"[3DCUO] EquipmentSidekickMap load FAILED: {ex}");
            }
        }

        private static string ResolveJsonPath()
        {
            // Same probing pattern as BaseMeshRegistry: build-output mirror first,
            // then walk up to the repo Data folder.
            string baseDir = AppContext.BaseDirectory;
            string[] candidates =
            {
                Path.Combine(baseDir, "Data", "uo-sidekick-map.json"),
                Path.Combine(baseDir, "..", "..", "..", "..", "..", "..", "Data", "uo-sidekick-map.json"),
                Path.Combine(baseDir, "..", "..", "..", "..", "Data", "uo-sidekick-map.json"),
            };
            foreach (var c in candidates)
            {
                if (File.Exists(c)) return Path.GetFullPath(c);
            }
            return null;
        }

        public static bool TryGetParts(ushort graphic, out List<SidekickPartRef> parts)
        {
            EnsureLoaded();
            return _byGraphic.TryGetValue(graphic, out parts);
        }

        public static void Invalidate()
        {
            _loaded = false;
            _byGraphic.Clear();
            _layerByGraphic.Clear();
            LoadedCount = 0;
            LastError = null;
        }
    }
}
