// SPDX-License-Identifier: BSD-2-Clause

using System;
using System.IO;
using ClassicUO.Utility.Logging;
using NAudio.Wave;

namespace ClassicUO.Game.Managers
{
    /// <summary>
    /// Plays per-persona NPC voice line MP3 files generated by the offline
    /// ElevenLabs synth pipeline.
    ///
    /// Triggered by server packet 0xBF / sub-command 0x0102. The server sends
    /// a repo-relative path of the form
    /// "audio/npc/personas/{persona_key}/{context}_{idx}_{hash}.mp3" — the
    /// client resolves it against {exe}/audio/ (the audio cache shipped with
    /// the client install).
    ///
    /// One line at a time — a new Play() call stops the previous line.
    /// NAudio's AudioFileReader handles both WAV and MP3 transparently.
    /// </summary>
    internal sealed class NpcVoiceManager : IDisposable
    {
        public static readonly NpcVoiceManager Instance = new NpcVoiceManager();

        // The server sends paths anchored at the repo root. The client copies
        // <repo>/audio/ to <exe>/audio/ at build time, so we resolve the path
        // relative to {exe}.
        private const string AudioRootSegment = "";

        private WaveOutEvent _waveOut;
        private AudioFileReader _currentFile;
        private float _volume = 0.8f;
        private bool _disposed;

        /// <summary>NPC voice volume (0–1). Persists across calls.</summary>
        public float Volume
        {
            get => _volume;
            set
            {
                _volume = Math.Clamp(value, 0f, 1f);
                if (_waveOut != null)
                    _waveOut.Volume = _volume;
            }
        }

        /// <summary>
        /// Play a voice line.
        /// relPath: repo-relative path as sent by the server, e.g.
        /// "audio/npc/personas/cb74c73a41be/greeting_0_8208edf5d62ba383.mp3".
        /// Resolved against {exe}/.
        /// Silently skips if the file does not exist.
        /// </summary>
        public void Play(string relPath)
        {
            if (string.IsNullOrEmpty(relPath))
                return;

            string fullPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                AudioRootSegment,
                relPath.Replace('/', Path.DirectorySeparatorChar)
            );

            if (!File.Exists(fullPath))
            {
                Log.Warn($"[NpcVoice] Missing: {fullPath}");
                return;
            }

            Stop();

            try
            {
                _currentFile = new AudioFileReader(fullPath) { Volume = _volume };
                _waveOut = new WaveOutEvent();
                _waveOut.Init(_currentFile);
                _waveOut.PlaybackStopped += (_, _) => Stop();
                _waveOut.Play();
                Log.Trace($"[NpcVoice] Playing: {relPath}");
            }
            catch (Exception ex)
            {
                Log.Error($"[NpcVoice] Playback failed for {relPath}: {ex.Message}");
                Stop();
            }
        }

        /// <summary>Stop and release the current audio file.</summary>
        public void Stop()
        {
            _waveOut?.Stop();
            _waveOut?.Dispose();
            _waveOut = null;
            _currentFile?.Dispose();
            _currentFile = null;
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            Stop();
        }
    }
}
